# Generated by Django 5.1.6 on 2025-03-02 09:11

import exchange.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_currencyexchangerate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xecredentials',
            options={'verbose_name': 'XE Credential', 'verbose_name_plural': 'XE Credentials'},
        ),
        migrations.AlterField(
            model_name='xecredentials',
            name='api_key',
            field=exchange.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='xecredentials',
            name='api_secret',
            field=exchange.fields.EncryptedCharField(max_length=255),
        ),
    ]
