# Generated by Django 5.1.6 on 2025-03-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyexchangerate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='currencyexchangerate',
            name='currency',
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='pair',
            field=models.CharField(default='', max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
