# Generated by Django 5.1.6 on 2025-03-03 16:00

import exchange.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_remove_currencyexchangerate_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateAPICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', exchange.fields.EncryptedCharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ExchangeRate-API Credential',
                'verbose_name_plural': 'ExchangeRate-API Credentials',
            },
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='pair',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
