# Generated by Django 5.1.6 on 2025-03-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_exchangerateapicredentials_alter_currency_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xecredentials',
            old_name='api_key',
            new_name='xe_api_key',
        ),
    ]
